name: MatchSplitter
options:
  bundleIdPrefix: com.matchsplitter
packages:
  EFQRCode:
    url: https://github.com/EFPrefix/EFQRCode.git
    from: 6.2.2
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS.git
    from: 8.0.0
targets:
  MatchSplitter:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - MatchSplitterApp.swift
      - Models
      - Views
      - ViewModels
      - Services
      - Assets.xcassets
    dependencies:
      - package: EFQRCode
      - package: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
        GIDClientID: 186631252201-k3dg32m7s5i0jqerp66880hvenb48c2o.apps.googleusercontent.com
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - com.googleusercontent.apps.186631252201-k3dg32m7s5i0jqerp66880hvenb48c2o
