import Foundation

struct Bank: Identifiable, Hashable {
    let id: String
    let name: String
    let shortName: String
    
    static let supportedBanks: [Bank] = [
        Bank(id: "970415", name: "Ngân hàng TMCP Công thương Việt Nam", shortName: "VietinBank"),
        Bank(id: "970436", name: "Ngân hàng TMCP Ngoại Thương Việt Nam", shortName: "Vietcombank"),
        Bank(id: "970418", name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam", shortName: "BIDV"),
        Bank(id: "970405", name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam", shortName: "Agribank"),
        Bank(id: "970448", name: "Ngân hàng TMCP Phương Đông", shortName: "OCB"),
        Bank(id: "970422", name: "Ngân hàng TMCP Quân đội", shortName: "MBBank"),
        Bank(id: "970407", name: "Ngân hàng TMCP Kỹ thương Việt Nam", shortName: "Techcombank"),
        Bank(id: "970416", name: "Ngân hàng TMCP Á Châu", shortName: "ACB"),
        Bank(id: "970432", name: "Ngân hàng TMCP Việt Nam Thịnh Vượng", shortName: "VPBank"),
        Bank(id: "970423", name: "Ngân hàng TMCP Tiên Phong", shortName: "TPBank"),
        Bank(id: "970403", name: "Ngân hàng TMCP Sài Gòn Thương Tín", shortName: "Sacombank"),
        Bank(id: "970437", name: "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh", shortName: "HDBank"),
        Bank(id: "970454", name: "Ngân hàng TMCP Bản Việt", shortName: "VietCapitalBank"),
        Bank(id: "970429", name: "Ngân hàng TMCP Sài Gòn", shortName: "SCB"),
        Bank(id: "970441", name: "Ngân hàng TMCP Quốc tế Việt Nam", shortName: "VIB"),
        Bank(id: "970443", name: "Ngân hàng TMCP Sài Gòn - Hà Nội", shortName: "SHB"),
        Bank(id: "970431", name: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam", shortName: "Eximbank"),
        Bank(id: "970426", name: "Ngân hàng TMCP Hàng Hải Việt Nam", shortName: "MSB"),
        Bank(id: "546034", name: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank", shortName: "CAKE"),
        Bank(id: "546035", name: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank", shortName: "Ubank"),
        Bank(id: "971005", name: "Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội", shortName: "ViettelMoney"),
        Bank(id: "963388", name: "Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)", shortName: "Timo"),
        Bank(id: "971011", name: "VNPT Money", shortName: "VNPTMoney"),
        Bank(id: "970400", name: "Ngân hàng TMCP Sài Gòn Công Thương", shortName: "SaigonBank"),
        Bank(id: "970409", name: "Ngân hàng TMCP Bắc Á", shortName: "BacABank"),
        Bank(id: "971025", name: "CTCP Dịch Vụ Di Động Trực Tuyến", shortName: "MoMo"),
        Bank(id: "971133", name: "Ngân hàng TMCP Đại Chúng Việt Nam Ngân hàng số", shortName: "PVcomBank Pay"),
        Bank(id: "970412", name: "Ngân hàng TMCP Đại Chúng Việt Nam", shortName: "PVcomBank"),
        Bank(id: "970414", name: "Ngân hàng TNHH MTV Việt Nam Hiện Đại", shortName: "MBV"),
        Bank(id: "970419", name: "Ngân hàng TMCP Quốc Dân", shortName: "NCB"),
        Bank(id: "970424", name: "Ngân hàng TNHH MTV Shinhan Việt Nam", shortName: "ShinhanBank"),
        Bank(id: "970425", name: "Ngân hàng TMCP An Bình", shortName: "ABBANK"),
        Bank(id: "970427", name: "Ngân hàng TMCP Việt Á", shortName: "VietABank"),
        Bank(id: "970428", name: "Ngân hàng TMCP Nam Á", shortName: "NamABank"),
        Bank(id: "970430", name: "Ngân hàng TMCP Thịnh vượng và Phát triển", shortName: "PGBank"),
        Bank(id: "970433", name: "Ngân hàng TMCP Việt Nam Thương Tín", shortName: "VietBank"),
        Bank(id: "970438", name: "Ngân hàng TMCP Bảo Việt", shortName: "BaoVietBank"),
        Bank(id: "970440", name: "Ngân hàng TMCP Đông Nam Á", shortName: "SeABank"),
        Bank(id: "970446", name: "Ngân hàng Hợp tác xã Việt Nam", shortName: "COOPBANK"),
        Bank(id: "970449", name: "Ngân hàng TMCP Lộc Phát Việt Nam", shortName: "LPBank"),
        Bank(id: "970452", name: "Ngân hàng TMCP Kiên Long", shortName: "KienLongBank"),
        Bank(id: "668888", name: "Ngân hàng Đại chúng TNHH Kasikornbank", shortName: "KBank"),
        Bank(id: "977777", name: "Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam)", shortName: "MAFC"),
        Bank(id: "970442", name: "Ngân hàng TNHH MTV Hong Leong Việt Nam", shortName: "HongLeong"),
        Bank(id: "970467", name: "Ngân hàng KEB Hana – Chi nhánh Hà Nội", shortName: "KEBHANAHN"),
        Bank(id: "970466", name: "Ngân hàng KEB Hana – Chi nhánh Thành phố Hồ Chí Minh", shortName: "KEBHanaHCM"),
        Bank(id: "533948", name: "Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội", shortName: "Citibank"),
        Bank(id: "970444", name: "Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam", shortName: "CBBank"),
        Bank(id: "422589", name: "Ngân hàng TNHH MTV CIMB Việt Nam", shortName: "CIMB"),
        Bank(id: "796500", name: "DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh", shortName: "DBSBank"),
        Bank(id: "970406", name: "Ngân hàng TNHH MTV Số Vikki", shortName: "Vikki"),
        Bank(id: "999888", name: "Ngân hàng Chính sách Xã hội", shortName: "VBSP"),
        Bank(id: "970408", name: "Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu", shortName: "GPBank"),
        Bank(id: "970463", name: "Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh", shortName: "KookminHCM"),
        Bank(id: "970462", name: "Ngân hàng Kookmin - Chi nhánh Hà Nội", shortName: "KookminHN"),
        Bank(id: "970457", name: "Ngân hàng TNHH MTV Woori Việt Nam", shortName: "Woori"),
        Bank(id: "970421", name: "Ngân hàng Liên doanh Việt - Nga", shortName: "VRB"),
        Bank(id: "458761", name: "Ngân hàng TNHH MTV HSBC (Việt Nam)", shortName: "HSBC"),
        Bank(id: "970455", name: "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội", shortName: "IBKHN"),
        Bank(id: "970456", name: "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh", shortName: "IBKHCM"),
        Bank(id: "970434", name: "Ngân hàng TNHH Indovina", shortName: "IndovinaBank"),
        Bank(id: "970458", name: "Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh", shortName: "UnitedOverseas"),
        Bank(id: "801011", name: "Ngân hàng Nonghyup - Chi nhánh Hà Nội", shortName: "Nonghyup"),
        Bank(id: "970410", name: "Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam", shortName: "StandardChartered"),
        Bank(id: "970439", name: "Ngân hàng TNHH MTV Public Việt Nam", shortName: "PublicBank")
    ]
}
