import Foundation

struct Bank: Identifiable, Hashable {
    let id: String
    let name: String
    let logoURL: String?
    let shortName: String
    
    static let supportedBanks: [Bank] = [
        Bank(id: "970415", name: "Ngân hàng TMCP Công thương Việt Nam", logoURL: "https://cdn.vietqr.io/img/ICB.png", shortName: "VietinBank"),
        Bank(id: "970436", name: "Ngân hàng TMCP Ngoại Thương Việt Nam", logoURL: "https://cdn.vietqr.io/img/VCB.png", shortName: "Vietcombank"),
        Bank(id: "970418", name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam", logoURL: "https://cdn.vietqr.io/img/BIDV.png", shortName: "BIDV"),
        Bank(id: "970405", name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam", logoURL: "https://cdn.vietqr.io/img/VBA.png", shortName: "Agribank"),
        Bank(id: "970448", name: "Ngân hàng TMCP Phương Đông", logoURL: "https://cdn.vietqr.io/img/OCB.png", shortName: "OCB"),
        Bank(id: "970422", name: "Ngân hàng TMCP Quân đội", logoURL: "https://cdn.vietqr.io/img/MB.png", shortName: "MBBank"),
        Bank(id: "970407", name: "Ngân hàng TMCP Kỹ thương Việt Nam", logoURL: "https://cdn.vietqr.io/img/TCB.png", shortName: "Techcombank"),
        Bank(id: "970416", name: "Ngân hàng TMCP Á Châu", logoURL: "https://cdn.vietqr.io/img/ACB.png", shortName: "ACB"),
        Bank(id: "970432", name: "Ngân hàng TMCP Việt Nam Thịnh Vượng", logoURL: "https://cdn.vietqr.io/img/VPB.png", shortName: "VPBank"),
        Bank(id: "970423", name: "Ngân hàng TMCP Tiên Phong", logoURL: "https://cdn.vietqr.io/img/TPB.png", shortName: "TPBank"),
        Bank(id: "970403", name: "Ngân hàng TMCP Sài Gòn Thương Tín", logoURL: "https://cdn.vietqr.io/img/STB.png", shortName: "Sacombank"),
        Bank(id: "970437", name: "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh", logoURL: "https://cdn.vietqr.io/img/HDB.png", shortName: "HDBank"),
        Bank(id: "970454", name: "Ngân hàng TMCP Bản Việt", logoURL: "https://cdn.vietqr.io/img/VCCB.png", shortName: "VietCapitalBank"),
        Bank(id: "970429", name: "Ngân hàng TMCP Sài Gòn", logoURL: "https://cdn.vietqr.io/img/SCB.png", shortName: "SCB"),
        Bank(id: "970441", name: "Ngân hàng TMCP Quốc tế Việt Nam", logoURL: "https://cdn.vietqr.io/img/VIB.png", shortName: "VIB"),
        Bank(id: "970443", name: "Ngân hàng TMCP Sài Gòn - Hà Nội", logoURL: "https://cdn.vietqr.io/img/SHB.png", shortName: "SHB"),
        Bank(id: "970431", name: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam", logoURL: "https://cdn.vietqr.io/img/EIB.png", shortName: "Eximbank"),
        Bank(id: "970426", name: "Ngân hàng TMCP Hàng Hải Việt Nam", logoURL: "https://cdn.vietqr.io/img/MSB.png", shortName: "MSB"),
        Bank(id: "546034", name: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank", logoURL: "https://cdn.vietqr.io/img/CAKE.png", shortName: "CAKE"),
        Bank(id: "546035", name: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank", logoURL: "https://cdn.vietqr.io/img/UBANK.png", shortName: "Ubank"),
        Bank(id: "971005", name: "Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội", logoURL: "https://cdn.vietqr.io/img/VIETTELMONEY.png", shortName: "ViettelMoney"),
        Bank(id: "963388", name: "Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)", logoURL: "https://vietqr.net/portal-service/resources/icons/TIMO.png", shortName: "Timo"),
        Bank(id: "971011", name: "VNPT Money", logoURL: "https://cdn.vietqr.io/img/VNPTMONEY.png", shortName: "VNPTMoney"),
        Bank(id: "970400", name: "Ngân hàng TMCP Sài Gòn Công Thương", logoURL: "https://cdn.vietqr.io/img/SGICB.png", shortName: "SaigonBank"),
        Bank(id: "970409", name: "Ngân hàng TMCP Bắc Á", logoURL: "https://cdn.vietqr.io/img/BAB.png", shortName: "BacABank"),
        Bank(id: "971025", name: "CTCP Dịch Vụ Di Động Trực Tuyến", logoURL: "https://cdn.vietqr.io/img/momo.png", shortName: "MoMo"),
        Bank(id: "971133", name: "Ngân hàng TMCP Đại Chúng Việt Nam Ngân hàng số", logoURL: "https://cdn.vietqr.io/img/PVCB.png", shortName: "PVcomBank Pay"),
        Bank(id: "970412", name: "Ngân hàng TMCP Đại Chúng Việt Nam", logoURL: "https://cdn.vietqr.io/img/PVCB.png", shortName: "PVcomBank"),
        Bank(id: "970414", name: "Ngân hàng TNHH MTV Việt Nam Hiện Đại", logoURL: "https://cdn.vietqr.io/img/MBV.png", shortName: "MBV"),
        Bank(id: "970419", name: "Ngân hàng TMCP Quốc Dân", logoURL: "https://cdn.vietqr.io/img/NCB.png", shortName: "NCB"),
        Bank(id: "970424", name: "Ngân hàng TNHH MTV Shinhan Việt Nam", logoURL: "https://cdn.vietqr.io/img/SHBVN.png", shortName: "ShinhanBank"),
        Bank(id: "970425", name: "Ngân hàng TMCP An Bình", logoURL: "https://cdn.vietqr.io/img/ABB.png", shortName: "ABBANK"),
        Bank(id: "970427", name: "Ngân hàng TMCP Việt Á", logoURL: "https://cdn.vietqr.io/img/VAB.png", shortName: "VietABank"),
        Bank(id: "970428", name: "Ngân hàng TMCP Nam Á", logoURL: "https://cdn.vietqr.io/img/NAB.png", shortName: "NamABank"),
        Bank(id: "970430", name: "Ngân hàng TMCP Thịnh vượng và Phát triển", logoURL: "https://cdn.vietqr.io/img/PGB.png", shortName: "PGBank"),
        Bank(id: "970433", name: "Ngân hàng TMCP Việt Nam Thương Tín", logoURL: "https://cdn.vietqr.io/img/VIETBANK.png", shortName: "VietBank"),
        Bank(id: "970438", name: "Ngân hàng TMCP Bảo Việt", logoURL: "https://cdn.vietqr.io/img/BVB.png", shortName: "BaoVietBank"),
        Bank(id: "970440", name: "Ngân hàng TMCP Đông Nam Á", logoURL: "https://cdn.vietqr.io/img/SEAB.png", shortName: "SeABank"),
        Bank(id: "970446", name: "Ngân hàng Hợp tác xã Việt Nam", logoURL: "https://cdn.vietqr.io/img/COOPBANK.png", shortName: "COOPBANK"),
        Bank(id: "970449", name: "Ngân hàng TMCP Lộc Phát Việt Nam", logoURL: "https://cdn.vietqr.io/img/LPB.png", shortName: "LPBank"),
        Bank(id: "970452", name: "Ngân hàng TMCP Kiên Long", logoURL: "https://cdn.vietqr.io/img/KLB.png", shortName: "KienLongBank"),
        Bank(id: "668888", name: "Ngân hàng Đại chúng TNHH Kasikornbank", logoURL: "https://cdn.vietqr.io/img/KBANK.png", shortName: "KBank"),
        Bank(id: "977777", name: "Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam)", logoURL: "https://cdn.vietqr.io/img/MAFC.png", shortName: "MAFC"),
        Bank(id: "970442", name: "Ngân hàng TNHH MTV Hong Leong Việt Nam", logoURL: "https://cdn.vietqr.io/img/HLBVN.png", shortName: "HongLeong"),
        Bank(id: "970467", name: "Ngân hàng KEB Hana – Chi nhánh Hà Nội", logoURL: "https://cdn.vietqr.io/img/KEBHANAHN.png", shortName: "KEBHANAHN"),
        Bank(id: "970466", name: "Ngân hàng KEB Hana – Chi nhánh Thành phố Hồ Chí Minh", logoURL: "https://cdn.vietqr.io/img/KEBHANAHCM.png", shortName: "KEBHanaHCM"),
        Bank(id: "533948", name: "Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội", logoURL: "https://cdn.vietqr.io/img/CITIBANK.png", shortName: "Citibank"),
        Bank(id: "970444", name: "Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam", logoURL: "https://cdn.vietqr.io/img/CBB.png", shortName: "CBBank"),
        Bank(id: "422589", name: "Ngân hàng TNHH MTV CIMB Việt Nam", logoURL: "https://cdn.vietqr.io/img/CIMB.png", shortName: "CIMB"),
        Bank(id: "796500", name: "DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh", logoURL: "https://cdn.vietqr.io/img/DBS.png", shortName: "DBSBank"),
        Bank(id: "970406", name: "Ngân hàng TNHH MTV Số Vikki", logoURL: "https://cdn.vietqr.io/img/Vikki.png", shortName: "Vikki"),
        Bank(id: "999888", name: "Ngân hàng Chính sách Xã hội", logoURL: "https://cdn.vietqr.io/img/VBSP.png", shortName: "VBSP"),
        Bank(id: "970408", name: "Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu", logoURL: "https://cdn.vietqr.io/img/GPB.png", shortName: "GPBank"),
        Bank(id: "970463", name: "Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh", logoURL: "https://cdn.vietqr.io/img/KBHCM.png", shortName: "KookminHCM"),
        Bank(id: "970462", name: "Ngân hàng Kookmin - Chi nhánh Hà Nội", logoURL: "https://cdn.vietqr.io/img/KBHN.png", shortName: "KookminHN"),
        Bank(id: "970457", name: "Ngân hàng TNHH MTV Woori Việt Nam", logoURL: "https://cdn.vietqr.io/img/WVN.png", shortName: "Woori"),
        Bank(id: "970421", name: "Ngân hàng Liên doanh Việt - Nga", logoURL: "https://cdn.vietqr.io/img/VRB.png", shortName: "VRB"),
        Bank(id: "458761", name: "Ngân hàng TNHH MTV HSBC (Việt Nam)", logoURL: "https://cdn.vietqr.io/img/HSBC.png", shortName: "HSBC"),
        Bank(id: "970455", name: "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội", logoURL: "https://cdn.vietqr.io/img/IBK.png", shortName: "IBKHN"),
        Bank(id: "970456", name: "Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh", logoURL: "https://cdn.vietqr.io/img/IBK.png", shortName: "IBKHCM"),
        Bank(id: "970434", name: "Ngân hàng TNHH Indovina", logoURL: "https://cdn.vietqr.io/img/IVB.png", shortName: "IndovinaBank"),
        Bank(id: "970458", name: "Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh", logoURL: "https://cdn.vietqr.io/img/UOB.png", shortName: "UnitedOverseas"),
        Bank(id: "801011", name: "Ngân hàng Nonghyup - Chi nhánh Hà Nội", logoURL: "https://cdn.vietqr.io/img/NHB.png", shortName: "Nonghyup"),
        Bank(id: "970410", name: "Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam", logoURL: "https://cdn.vietqr.io/img/SCVN.png", shortName: "StandardChartered"),
        Bank(id: "970439", name: "Ngân hàng TNHH MTV Public Việt Nam", logoURL: "https://cdn.vietqr.io/img/PBVN.png", shortName: "PublicBank")
    ]
}
